version: '2'

services:
  web:
    image: nginx:1.17-alpine
    ports:
      - 80:80
    volumes_from:
      - php:ro
    volumes:
      - ./config/nginx/includes:/etc/nginx/includes
      - ./config/nginx/frontend.conf:/etc/nginx/conf.d/default.conf

  php:
    image: fmrng/php:7.4
    build:
      context: ./config/php
      dockerfile: Dockerfile.74
    environment:
      COMPOSER_HOME: /var/www/.data/composer
      TZ: Europe/Berlin
    volumes:
      - .:/var/www
      - ./config/php/php.ini:/usr/local/etc/php/php.ini

  database:
    image: mariadb:10.3
    environment:
      MYSQL_DATABASE: magento
      MYSQL_ROOT_PASSWORD: password
      TZ: Europe/Berlin
    ports:
      - 3306:3306
    volumes:
      - .data/mysql:/var/lib/mysql

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
    environment:
      discovery.type: 'single-node'
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"
      TZ: Europe/Berlin
    volumes:
      - .data/elasticsearch:/usr/share/elasticsearch/data

  cache:
    image: redis:latest
