FROM php:7.1-fpm
LABEL maintainer="francesco.marangi@gmail.com"

RUN buildDeps=" \
        default-mysql-client \
         libcurl4-openssl-dev \
        libpng-dev \
        libjpeg-dev \
        libicu-dev \
        libpcre3-dev \
        libmcrypt-dev \
        libxml2-utils \
        libxslt1-dev \
        libfreetype6-dev \
        freetype* \
        openssh-client \
        openssl \
        procps \
        rsync \
    "; \
    phpExt=" \
        bcmath \
        ctype \
        curl \
        dom \
        json \
        gd \
        hash \
        iconv \
        intl \
        mbstring \
        mcrypt \
        pdo_mysql \
        soap \
        xml \
        xsl \
        zip \
    "; \
    set -x \
    && apt-get update && apt-get install -y $buildDeps --no-install-recommends \
    && rm -rf /var/lib/apt/lists/* \
    && docker-php-ext-configure gd --with-png-dir=/usr --with-jpeg-dir=/usr --with-freetype-dir \
    && docker-php-ext-install $phpExt \
    && apt-get purge -y --auto-remove

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin/ --filename=composer

# Install n98-magerun2.phar and move to /usr/bin/
RUN curl -O https://files.magerun.net/n98-magerun2.phar && chmod +x ./n98-magerun2.phar && mv ./n98-magerun2.phar /usr/bin/
